title: Greg Ferraro
logo: gf_Headshot.jpg
description: “History itself was a massive n = 1 study, irreproducible. It was what made it so difficult to learn from.” - James S. A. Corey
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Define navigation menu
nav:
  - name: "Home"
    link: "/"
  - name: "Research"
    link: "/research"
