title: Greg Ferraro
logo: gf_Headshot.jpg
description: Experienced studying rural development and environmental health; I enjoy reading about political economy, organizational psychology, and decision making. 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
