title: Greg Ferraro
logo: gf_Headshot.jpg
description: Greg's page
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Define navigation menu
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
