title: Greg Ferraro
description: Greg's page
logo: gf_Headshot.jpg

# Use a theme (you can keep Minimal or another GitHub Pages theme)
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Define navigation menu
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
