title: Greg Ferraro
logo: gf_Headshot.jpg
description: An aspiring researcher, I have experience studying rural development and environmental health. I enjoy reading about political economy, organizational psychology, and decision making behavior. 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

author:
  location: "Raleigh, North Carolina, USA"
  linkedin: "greg-ferraro-23164b2b"
